apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/iyesdendeni/idsp-argocd.git
      targetRevision: main
      path: manifests/logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
