apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ssp
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: mysql
      targetRevision: 12.3.5
      helm:
        valueFiles:
          - $values/values/mysql-values.yaml
    - repoURL: ${GIT_REPO_URL}
      targetRevision: main
      ref: values
    - repoURL: ${GIT_REPO_URL}
      targetRevision: main
      path: manifests
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
