apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssp-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: ssp
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: ssp-infra
      repoURL: ${SSP_HELM_REPO_URL}
      targetRevision: ${CHART_VERSION}
      helm:
        valueFiles:
          - $values/values/ssp-infra-values.yaml
    - repoURL: ${GIT_REPO_URL}
      targetRevision: main
      ref: values
    - repoURL: ${GIT_REPO_URL}
      targetRevision: main
      path: manifests/ssp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
