---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluent-bit-elastic-credentials
  namespace: ssp
spec:
  encryptedData:
    password: AgB0zqTMfy1Z8C5Kvjrj8vgQg33RvteTnOcWP9j++SJmHCg8kA4eNlCAIufGSobePPEDbABSeWgibutNHQkfS2c5lQSwe6h3f+IWJFZ6Z/U39nvjRK38VA7Ow8zjKjeckAIZGRQuwueklGZb2VdDKnczoc+2OADtSwhZZ0vzKEO89tJdNSiufRkEWd+4Y7qWJIt1dJ2lwTQ7uJz5zyPYwiL42WcOPOBGwmLcUObG/mbIJNQ3gTD1EPvn+RdDj5bzhgtbhv2dD+8u2bS4Koz+AK3an00+Fk1ysQovPq+1KweXEnpTdMZdl/xAnDsFw/P1n4s1DrsPzHAxbMU/Z0rSr3VwYZxh4Kr9rn1knfXJg3iI7WTBRaBaxVmMEDq7ARCsUCPRmVvZZVV/2J0xCOvyd1B1ylRGtf/Xto4fty5aWvpSzzsIoeTrzrRzAMkddI1HkEl4jCeQcR+Eg5gHt+9R5W9BE3NpAw9oDcY/PUwW8VQ8+/TYNek9Wt3p2RRogKg8csrZibnaFEEY2lsDEYZHMzWp8E56ZS65IIV0CU0tOLcGyAKBa9orRfraIb4P72LUDyHSAtpq0HfFXjWkTf8IvzyRjBn/hnx53P1pDegKNxUu3G0tc/KAgTs6EWDr+gP6/VPNHo59+DfdzQ2io5AtC2B2uPJb8PH9rVoJ88r5aiPAbU4exvV2R6noCmHVpML2biB++/QznJQsP//Y
  template:
    metadata:
      name: fluent-bit-elastic-credentials
      namespace: ssp
